### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by mami-inuzuka** [mami-inuzuka/seppanda#6]
* Groupは不要でUserに直接Transaction_idを持たせるでもよいかも？
* でもそうすると一つのTransactionに何人紐付けられるかの制御がしづらい？
（最初は2名での利用を想定し、将来的に複数人で使えるようにはしたい）

<img width="944" alt="スクリーンショット 2021-10-20 20 21 05" src="https://user-images.githubusercontent.com/52844263/138083672-c3acf813-1b9a-43d6-9a0a-e16e8466ca3d.png">

**Comment by cafedomancer** [comment]
* FB: パスワードは保存するとまずいのでパスワードダイジェスト (パスワードをハッシュ化したもの) にしておくと良さそう

**Comment by mami-inuzuka** [comment]
何度も非常に丁寧なレビューをしていただいて本当にありがとうございます🙇🏻‍♂️

>ペアリングとワークスペースの関係が逆かも？と思いました。

こちらはちょうど今Railsの復習をする中で関連付けについて改めて理解し、
ご指摘の意味も理解できました！
確かに外部キーを持つテーブルはペアリングテーブルのほうになると思うので直しておきます✨😊

そして名前付けのところも確かに...と思いました><
今日実際にペアリング機能の部分だけ試しに実装してみていたのですが、
確かに実装する中で`belongings`は`parings`の方がしっくりくるなあなど感じたので、確かに全体的にもっとわかりやすい名前がありそうです！一旦今の名前で進めつつ考えたいと思います！！

いったん暫定でこちらのDB設計を元に進めたいと思います🙌
<img width="702" alt="スクリーンショット 2021-10-31 17 47 43" src="https://user-images.githubusercontent.com/52844263/139575004-9b3106e4-8378-49f6-a09a-eb1ee547bd77.png">

**Comment by mami-inuzuka** [comment]
こまがたさんからコメントをいただいてもう少しシンプルな設計にしました
<img width="1378" alt="スクリーンショット 2021-11-01 16 38 31" src="https://user-images.githubusercontent.com/52844263/139637812-643daf4a-159e-4190-b075-142b2f6c95f3.png">
